"""
Payroll Models — SalaryStructure, StaffSalaryAssignment, Payslip
"""
import enum
from sqlalchemy import Column, String, Date, Boolean, Text, Integer, DateTime, ForeignKey, Numeric
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.models.base import TenantBaseModel, SoftDeleteMixin


class PayslipStatus(str, enum.Enum):
    PENDING = "pending"
    PAID = "paid"
    ON_HOLD = "on_hold"
    CANCELLED = "cancelled"


class PaymentMode(str, enum.Enum):
    BANK_TRANSFER = "bank_transfer"
    CASH = "cash"
    CHEQUE = "cheque"


class SalaryStructure(TenantBaseModel, SoftDeleteMixin):
    """
    Reusable pay grade template. E.g. 'Grade A – Teaching', 'Grade B – Support'.
    Allowances and deductions stored as JSON:
        allowances = {"hra": {"type": "percent", "value": 20}, "ta": {"type": "fixed", "value": 1000}}
        deductions  = {"pf": {"type": "percent", "value": 12}, "tds": {"type": "percent", "value": 10}}
    """
    __tablename__ = "salary_structures"

    name = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)
    base_salary = Column(Numeric(12, 2), nullable=False)

    # JSON maps:  component_name → {type: "percent"|"fixed", value: float}
    allowances = Column(JSONB, nullable=False, server_default='{}')
    deductions = Column(JSONB, nullable=False, server_default='{}')

    is_active = Column(Boolean, default=True, nullable=False)

    assignments = relationship("StaffSalaryAssignment", back_populates="structure",
                               lazy="dynamic")


class StaffSalaryAssignment(TenantBaseModel, SoftDeleteMixin):
    """Links a staff member to a SalaryStructure, with optional base salary override."""
    __tablename__ = "staff_salary_assignments"

    staff_id = Column(UUID(as_uuid=True), ForeignKey("staff.id", ondelete="CASCADE"),
                      nullable=False, index=True)
    structure_id = Column(UUID(as_uuid=True), ForeignKey("salary_structures.id", ondelete="RESTRICT"),
                          nullable=False, index=True)

    effective_from = Column(Date, nullable=False)
    effective_to = Column(Date, nullable=True)   # null = currently active
    custom_base_salary = Column(Numeric(12, 2), nullable=True)  # overrides structure base if set
    bank_account_number = Column(String(50), nullable=True)
    bank_name = Column(String(100), nullable=True)
    ifsc_code = Column(String(20), nullable=True)
    pan_number = Column(String(20), nullable=True)

    structure = relationship("SalaryStructure", back_populates="assignments")
    staff = relationship("Staff", foreign_keys=[staff_id], lazy="joined")
    payslips = relationship("Payslip", back_populates="assignment", lazy="dynamic")


class Payslip(TenantBaseModel, SoftDeleteMixin):
    """
    One payslip per staff per month. Generated by the payroll run.
    Stores a snapshot of computed values at the time of generation.
    """
    __tablename__ = "payslips"

    staff_id = Column(UUID(as_uuid=True), ForeignKey("staff.id", ondelete="CASCADE"),
                      nullable=False, index=True)
    assignment_id = Column(UUID(as_uuid=True),
                           ForeignKey("staff_salary_assignments.id", ondelete="SET NULL"),
                           nullable=True)

    month = Column(Integer, nullable=False)   # 1–12
    year = Column(Integer, nullable=False)

    # Computed snapshot (stored so changes to structure don't affect past payslips)
    base_salary = Column(Numeric(12, 2), nullable=False)
    gross_salary = Column(Numeric(12, 2), nullable=False)
    total_deductions = Column(Numeric(12, 2), nullable=False, server_default='0')
    net_salary = Column(Numeric(12, 2), nullable=False)

    # Breakdown snapshots
    allowances_breakdown = Column(JSONB, nullable=False, server_default='{}')
    deductions_breakdown = Column(JSONB, nullable=False, server_default='{}')

    # Adjustments (LOP, overtime, bonuses)
    days_worked = Column(Integer, nullable=True)
    loss_of_pay_days = Column(Integer, default=0)
    loss_of_pay_amount = Column(Numeric(12, 2), default=0)
    bonus = Column(Numeric(12, 2), default=0)
    advance_deduction = Column(Numeric(12, 2), default=0)

    # Payment info
    status = Column(String(20), default=PayslipStatus.PENDING, nullable=False, index=True)
    payment_mode = Column(String(30), nullable=True)
    paid_at = Column(DateTime, nullable=True)
    paid_by = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    remarks = Column(Text, nullable=True)

    staff = relationship("Staff", foreign_keys=[staff_id], lazy="joined")
    assignment = relationship("StaffSalaryAssignment", back_populates="payslips")
