"""add_school_class_and_relationships

Revision ID: 91c67cbe234c
Revises: 20260110_audit_softdelete
Create Date: 2026-01-14 11:40:13.719399+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91c67cbe234c'
down_revision: Union[str, None] = '20260110_audit_softdelete'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_is_deleted', table_name='attendance')
    op.create_unique_constraint(None, 'attendance', ['id'])
    op.create_unique_constraint(None, 'calendar_events', ['id'])
    op.create_unique_constraint(None, 'certificate_templates', ['id'])
    op.create_unique_constraint(None, 'certificates', ['id'])
    op.create_unique_constraint(None, 'courses', ['id'])
    op.create_unique_constraint(None, 'exam_results', ['id'])
    op.create_unique_constraint(None, 'examinations', ['id'])
    op.alter_column('fee_discounts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'fee_discounts', ['id'])
    op.alter_column('fee_payments', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'fee_payments', ['id'])
    op.alter_column('fee_structures', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'fee_structures', ['id'])
    op.create_unique_constraint(None, 'grade_levels', ['id'])
    op.create_unique_constraint(None, 'grade_scales', ['id'])
    op.create_unique_constraint(None, 'hostel_beds', ['id'])
    op.create_unique_constraint(None, 'hostel_fees', ['id'])
    op.create_unique_constraint(None, 'hostel_mess_menus', ['id'])
    op.create_unique_constraint(None, 'hostel_room_allocations', ['id'])
    op.create_unique_constraint(None, 'hostel_rooms', ['id'])
    op.create_unique_constraint(None, 'hostels', ['id'])
    op.create_unique_constraint(None, 'library_book_copies', ['id'])
    op.create_unique_constraint(None, 'library_book_issues', ['id'])
    op.create_unique_constraint(None, 'library_books', ['id'])
    op.create_unique_constraint(None, 'library_members', ['id'])
    op.create_unique_constraint(None, 'library_settings', ['id'])
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_messages_recipient', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_status', table_name='messages')
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'messages', ['id'])
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'is_deleted')
    op.create_unique_constraint(None, 'modules', ['id'])
    op.create_unique_constraint(None, 'notification_preferences', ['id'])
    op.create_unique_constraint(None, 'notification_templates', ['id'])
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.create_unique_constraint(None, 'parent_students', ['id'])
    op.create_unique_constraint(None, 'payment_gateway_configs', ['id'])
    op.create_unique_constraint(None, 'payment_notifications', ['id'])
    op.create_unique_constraint(None, 'payment_orders', ['id'])
    op.create_unique_constraint(None, 'payment_refunds', ['id'])
    op.create_unique_constraint(None, 'payment_transactions', ['id'])
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.alter_column('refresh_tokens', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    # Use raw SQL with USING clause for PostgreSQL enum type conversion
    op.execute("ALTER TABLE reports ALTER COLUMN report_type TYPE reporttype USING report_type::reporttype")
    op.execute("ALTER TABLE reports ALTER COLUMN format TYPE reportformat USING format::reportformat")
    op.execute("ALTER TABLE reports ALTER COLUMN status TYPE reportstatus USING status::reportstatus")
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_type', table_name='reports')
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'reports', ['id'])
    op.drop_column('reports', 'deleted_at')
    op.drop_column('reports', 'is_deleted')
    op.create_unique_constraint(None, 'role_module_access', ['id'])
    op.create_unique_constraint(None, 'role_permissions', ['id'])
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'rooms', ['id'])
    op.create_unique_constraint(None, 'school_classes', ['id'])
    op.create_unique_constraint(None, 'staff', ['id'])
    op.create_unique_constraint(None, 'student_gpas', ['id'])
    op.create_unique_constraint(None, 'student_transport', ['id'])
    op.add_column('students', sa.Column('class_id', sa.UUID(), nullable=True))
    op.alter_column('students', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_students_user_id', table_name='students')
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_unique_constraint(None, 'students', ['id'])
    op.drop_constraint('students_user_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'school_classes', ['class_id'], ['id'])
    op.drop_column('students', 'user_id')
    op.create_unique_constraint(None, 'subscription_plans', ['id'])
    op.create_unique_constraint(None, 'tenant_modules', ['id'])
    op.create_unique_constraint(None, 'tenants', ['id'])
    op.create_unique_constraint(None, 'time_slots', ['id'])
    op.create_unique_constraint(None, 'timetable_conflicts', ['id'])
    op.create_unique_constraint(None, 'timetable_entries', ['id'])
    op.create_unique_constraint(None, 'transport_fees', ['id'])
    op.create_unique_constraint(None, 'transport_route_stops', ['id'])
    op.create_unique_constraint(None, 'transport_routes', ['id'])
    op.create_unique_constraint(None, 'transport_vehicles', ['id'])
    op.create_unique_constraint(None, 'user_roles', ['id'])
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint(None, 'transport_vehicles', type_='unique')
    op.drop_constraint(None, 'transport_routes', type_='unique')
    op.drop_constraint(None, 'transport_route_stops', type_='unique')
    op.drop_constraint(None, 'transport_fees', type_='unique')
    op.drop_constraint(None, 'timetable_entries', type_='unique')
    op.drop_constraint(None, 'timetable_conflicts', type_='unique')
    op.drop_constraint(None, 'time_slots', type_='unique')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_constraint(None, 'tenant_modules', type_='unique')
    op.drop_constraint(None, 'subscription_plans', type_='unique')
    op.add_column('students', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_user_id_fkey', 'students', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.alter_column('students', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('students', 'class_id')
    op.drop_constraint(None, 'student_transport', type_='unique')
    op.drop_constraint(None, 'student_gpas', type_='unique')
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_constraint(None, 'school_classes', type_='unique')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'role_permissions', type_='unique')
    op.drop_constraint(None, 'role_module_access', type_='unique')
    op.add_column('reports', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.create_index('idx_reports_type', 'reports', ['report_type'], unique=False)
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='reportstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('reports', 'format',
               existing_type=sa.Enum('PDF', 'EXCEL', 'CSV', 'JSON', name='reportformat'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'json'::character varying"))
    op.alter_column('reports', 'report_type',
               existing_type=sa.Enum('STUDENT_LIST', 'ATTENDANCE_SUMMARY', 'FEE_COLLECTION', 'FEE_DEFAULTERS', 'STAFF_LIST', 'EXAM_RESULTS', 'CUSTOM', name='reporttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'custom'::character varying"))
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.alter_column('refresh_tokens', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'payment_transactions', type_='unique')
    op.drop_constraint(None, 'payment_refunds', type_='unique')
    op.drop_constraint(None, 'payment_orders', type_='unique')
    op.drop_constraint(None, 'payment_notifications', type_='unique')
    op.drop_constraint(None, 'payment_gateway_configs', type_='unique')
    op.drop_constraint(None, 'parent_students', type_='unique')
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_constraint(None, 'notification_templates', type_='unique')
    op.drop_constraint(None, 'notification_preferences', type_='unique')
    op.drop_constraint(None, 'modules', type_='unique')
    op.add_column('messages', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.create_index('idx_messages_status', 'messages', ['status'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_recipient', 'messages', ['recipient_id'], unique=False)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'library_settings', type_='unique')
    op.drop_constraint(None, 'library_members', type_='unique')
    op.drop_constraint(None, 'library_books', type_='unique')
    op.drop_constraint(None, 'library_book_issues', type_='unique')
    op.drop_constraint(None, 'library_book_copies', type_='unique')
    op.drop_constraint(None, 'hostels', type_='unique')
    op.drop_constraint(None, 'hostel_rooms', type_='unique')
    op.drop_constraint(None, 'hostel_room_allocations', type_='unique')
    op.drop_constraint(None, 'hostel_mess_menus', type_='unique')
    op.drop_constraint(None, 'hostel_fees', type_='unique')
    op.drop_constraint(None, 'hostel_beds', type_='unique')
    op.drop_constraint(None, 'grade_scales', type_='unique')
    op.drop_constraint(None, 'grade_levels', type_='unique')
    op.drop_constraint(None, 'fee_structures', type_='unique')
    op.alter_column('fee_structures', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'fee_payments', type_='unique')
    op.alter_column('fee_payments', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'fee_discounts', type_='unique')
    op.alter_column('fee_discounts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'examinations', type_='unique')
    op.drop_constraint(None, 'exam_results', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'certificates', type_='unique')
    op.drop_constraint(None, 'certificate_templates', type_='unique')
    op.drop_constraint(None, 'calendar_events', type_='unique')
    op.drop_constraint(None, 'attendance', type_='unique')
    op.create_index('ix_attendance_is_deleted', 'attendance', ['is_deleted'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.ENUM('create', 'read', 'update', 'delete', 'login', 'logout', 'failed_login', 'password_change', 'permission_change', 'export', 'import', name='auditaction'), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='audit_logs_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
